package com.jazz.drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer UUID;

	public RuleObject() {
	}

	public java.lang.Integer getUUID() {
		return this.UUID;
	}

	public void setUUID(java.lang.Integer UUID) {
		this.UUID = UUID;
	}

	public RuleObject(java.lang.Integer UUID) {
		this.UUID = UUID;
	}

}