package com.jazz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderDiscount implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer discount=0;

	public OrderDiscount() {
	}

	public java.lang.Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.Integer discount) {
		this.discount = discount;
	}

	public OrderDiscount(java.lang.Integer discount) {
		this.discount = discount;
	}

}