package com.jazz.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;

	private java.lang.Integer amount;

	private java.lang.String customerNumber;

	private com.jazz.model.CustomerType customerType;

	public OrderRequest() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public java.lang.String getCustomerNumber() {
		return this.customerNumber;
	}

	public void setCustomerNumber(java.lang.String customerNumber) {
		this.customerNumber = customerNumber;
	}

	public com.jazz.model.CustomerType getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(com.jazz.model.CustomerType customerType) {
		this.customerType = customerType;
	}

	public OrderRequest(java.lang.Integer age, java.lang.Integer amount,
			java.lang.String customerNumber,
			com.jazz.model.CustomerType customerType) {
		this.age = age;
		this.amount = amount;
		this.customerNumber = customerNumber;
		this.customerType = customerType;
	}

}